keyword_dict = {
    "harappan": "Harappan Civilization",
    "mohenjo-daro": "Harappan Civilization",
    "ashoka": "Ashokan Edicts",
    "edict": "Mauryan Empire",
    "chandragup": "Mauryan Empire",
    "urban planning": "Urban Planning",
    "ghatika": "Temple-based Education",
    "burzahom": "Archaeological Site – Burzahom",
    "copper": "Material Culture of Chalcolithic & Harappan Sites",
    "sine": "History of Indian Mathematics",
    "surgical": "History of Indian Science",
}
keyword_dict.update({
    "mixed economy": "Types of Economic Systems",
    "market economy": "Types of Economic Systems",
    "planned economy": "Types of Economic Systems",
    "private": "Private Sector Role",
    "public sector": "Public Sector Role",
    "gdp": "Macroeconomic Indicators",
    "national income": "Macroeconomic Indicators",
    "inflation": "Inflation and Price Stability",
    "unemployment": "Employment & Labor Economics",
    "tax": "Fiscal Policy",
    "budget": "Fiscal Policy",
    "monetary policy": "Monetary Policy",
    "interest rate": "Monetary Policy",
    "import": "International Trade",
    "export": "International Trade",
    "balance of payments": "External Sector",
})
keyword_dict.update({
    "derivative": "Calculus – Differentiation",
    "integration": "Calculus – Integration",
    "limit": "Calculus – Limits",
    "polynomial": "Algebra – Polynomials",
    "quadratic": "Algebra – Quadratic Equations",
    "angle": "Geometry – Angles",
    "triangle": "Geometry – Triangles",
    "circle": "Geometry – Circles",
    "cyclic quadrilateral": "Geometry – Cyclic Quadrilaterals",
    "sin": "Trigonometry",
    "cos": "Trigonometry",
    "tan": "Trigonometry",
    "irrational": "Number Theory – Real Numbers",
    "prime": "Number Theory – Prime Numbers",
})
keyword_dict.update({
    "newton": "Laws of Motion",
    "force": "Classical Mechanics",
    "acceleration": "Kinematics",
    "uniform motion": "Kinematics",
    "circular motion": "Rotational Motion",
    "voltage": "Electricity",
    "current": "Electricity",
    "resistance": "Electricity",
    "ohm": "Ohm’s Law",
    "temperature": "Thermodynamics",
    "entropy": "Thermodynamics",
    "electron": "Atomic Structure",
    "photon": "Quantum Physics",
    "reflection": "Ray Optics",
    "refraction": "Ray Optics",
    "lens": "Geometrical Optics",
})
